variables:
    EXTRA_DOCKER_RUN_ARGS: "--ipc=host --ulimit memlock=-1 --ulimit stack=$$((1024*65536))"
    DATADIR: ${DATA_DIR}
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive
    GET_SOURCES_ATTEMPTS: 3

stages:
    - build
    - test

before_script:
    - echo "${CI_BUILD_NAME}" | grep -Eq "(^|-)py2($|-)" && export PYVER=2.7 || export PYVER=3.6   && echo "${PYVER}"
    - export NV_DOCKER_ARGS="curl -s http://localhost:${DOCKER_PORT}/docker/cli?dev=${RUNNER_GPUS//,/+}"     && echo "${NV_DOCKER_ARGS}"
    - export RELEASE_BRANCH_IN_IMAGE=${CI_COMMIT_REF_SLUG%%}                                       && echo "${RELEASE_BRANCH_IN_IMAGE}"
    - export IMAGE_NAME_ROOT="${CI_REGISTRY_IMAGE}:${RELEASE_BRANCH_IN_IMAGE}-py${PYVER%.*}"       && echo "${IMAGE_NAME_ROOT}"
    - export MASTER_BASE_IMAGE_NAME="${CI_REGISTRY_IMAGE}:master-py${PYVER%.*}"                    && echo "${MASTER_BASE_IMAGE_NAME}"
    - export BASE_IMAGE_NAME="${IMAGE_NAME_ROOT}"                                                  && echo "${BASE_IMAGE_NAME}"
    - export BASE_IMAGE_NAME_VERSIONED="${IMAGE_NAME_ROOT}.${CI_PIPELINE_ID}"                      && echo "${BASE_IMAGE_NAME_VERSIONED}"
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

################
# Build Section
################
.base_template : &BASE
    stage: build
    script:
    - echo -e "FROM pytorch/pytorch:${PYTORCH_UPSTREAM_CONTAINER_TAG}\n"
              "WORKDIR /opt/apex\n"
              "COPY . .\n"
              "RUN pip install -v --no-cache-dir --global-option=\"--cpp_ext\" --global-option=\"--cuda_ext\" .\n"
              "WORKDIR /workspace\n"
        > Dockerfile.${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}
    - docker pull "${BASE_IMAGE_NAME}" ||
      docker pull "${MASTER_BASE_IMAGE_NAME}" || true
    - docker build --pull
                   --cache-from "${BASE_IMAGE_NAME}"
                   --cache-from "${MASTER_BASE_IMAGE_NAME}"
                   -t "${BASE_IMAGE_NAME}-${APEX_CONTAINER_TAG}"
                   -t "${BASE_IMAGE_NAME_VERSIONED}-${APEX_CONTAINER_TAG}"
                   -f Dockerfile.${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG} .
    - docker push "${BASE_IMAGE_NAME}-${APEX_CONTAINER_TAG}"
    - docker push "${BASE_IMAGE_NAME_VERSIONED}-${APEX_CONTAINER_TAG}"
    except:
    - tags

py3-pytorch-nightly:
    <<: *BASE
    variables:
      PYTORCH_UPSTREAM_CONTAINER_TAG: nightly-devel-cuda10.0-cudnn7
      APEX_CONTAINER_TAG: torch-nightly

py3-pytorch-1-0:
    <<: *BASE
    variables:
      PYTORCH_UPSTREAM_CONTAINER_TAG: 1.0-cuda10.0-cudnn7-devel
      APEX_CONTAINER_TAG: torch-1-0

################
# Test Section
################
# base test script
.test_template: &TEST_TEMPLATE
    stage: test
    script:
    - export TEST_WORK_DIR="${TEST_WORK_DIR%%--*}"
    - export CONTAINER_NAME="${CI_PROJECT_NAME}.${CI_JOB_ID}.${CI_JOB_NAME}"
    - cat /proc/driver/nvidia/version
    - docker pull "${BASE_IMAGE_NAME_VERSIONED}-${APEX_CONTAINER_TAG}"
    - ( sleep 10800 && echo "******TIMEOUT EXPIRED******" && docker kill "${CONTAINER_NAME}" ) &
      set -x &&
      docker run $(eval ${NV_DOCKER_ARGS})
             --name "${CONTAINER_NAME}"
             -v $DATADIR:/opt/home/apex/examples/
             $(eval echo ${EXTRA_DOCKER_RUN_ARGS})
             -w ${TEST_WORK_DIR}
             ${BASE_IMAGE_NAME_VERSIONED}-${APEX_CONTAINER_TAG}
             /bin/bash -c "nvidia-smi && ${TEST_COMMAND}" || RV=$?;
      set +x;
      docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1;
      pkill -HUP sleep >/dev/null 2>&1 || true;
      exit ${RV:-0}
    artifacts:
      name: "${CI_JOB_NAME}"
      expire_in: 3 days
      when: always
    tags:
    - must_specify_runner
    except:
    - tags
    allow_failure: false

# runner configs
.TU102_R410_2GPU: &TU102_R410_2GPU
    tags:
    - TU102
    - R410
    - 2GPU

.TU104_R418_2GPU: &TU104_R418_2GPU
    tags:
    - TU104
    - R418
    - 2GPU

.V100_R410_4GPU: &V100_R410_4GPU
    tags:
    - V100
    - R410
    - 4GPU

.P100_R384_4GPU: &P100_R384_4GPU
    tags:
    - P100
    - R384
    - 4GPU

.P40_R384_2GPU: &P40_R384_2GPU
    tags:
    - P40
    - R384
    - 2GPU

.M40_R384_2GPU: &M40_R384_2GPU
    tags:
    - M40
    - R384
    - 2GPU

# defines default test dirs and commands
.L0_test: &L0_TEST
    <<: *TEST_TEMPLATE

.L0_test_variables: &L0_test_variables
    variables:
      TEST_WORK_DIR: /opt/apex/tests/L0/
      TEST_COMMAND: python run_test.py

.L1_cross_product_test: &L1_CROSS_PRODUCT
    <<: *TEST_TEMPLATE

.L1_cross_product_test_variables: &L1_cross_product_test_variables
    variables:
      TEST_WORK_DIR: /opt/apex/tests/L1/cross_product/
      TEST_COMMAND: ./run.sh

.L1_cross_product_distributed_test: &L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *TEST_TEMPLATE

.L1_cross_product_distributed_test_variables: &L1_cross_product_distributed_test_variables
    variables:
      TEST_WORK_DIR: /opt/apex/tests/L1/cross_product_distributed/
      TEST_COMMAND: ./run.sh

.distributed_ddp_test: &DISTRIBUTED_DDP
    <<: *TEST_TEMPLATE

.distributed_ddp_test_variables: &distributed_ddp_test_variables
    variables:
      TEST_WORK_DIR: /opt/apex/tests/distributed/DDP/
      TEST_COMMAND: ./run_race_test.sh

.distributed_synced_batchnorm_test: &DISTRIBUTED_SYNCED_BATCHNORM
    <<: *TEST_TEMPLATE

.distributed_synced_batchnorm_test_variables: &distributed_synced_batchnorm_test_variables
    variables:
      TEST_WORK_DIR: /opt/apex/tests/distributed/synced_batchnorm/
      TEST_COMMAND: ./unit_test.sh

##########################
# Test runs for nightlies
##########################
#### Turing (TU102) runs ####
tests_L0--TU102_R410_2GPU--torch-nightly:
    <<: *L0_TEST
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--TU102_R410_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--TU102_R410_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--TU102_R410_2GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--TU102_R410_2GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### Turing (TU104) runs ####
tests_L0--TU104_R418_2GPU--torch-nightly:
    <<: *L0_TEST
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--TU104_R418_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--TU104_R418_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--TU104_R418_2GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--TU104_R418_2GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### Volta runs ####
tests_L0--V100_R410_4GPU--torch-nightly:
    <<: *L0_TEST
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--V100_R410_4GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--V100_R410_4GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--V100_R410_4GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--V100_R410_4GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables

#### P100 runs ####
tests_L0--P100_R384_4GPU--torch-nightly:
    <<: *L0_TEST
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--P100_R384_4GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--P100_R384_4GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--P100_R384_4GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--P100_R384_4GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables

#### P40 runs ####
tests_L0--P40_R384_2GPU--torch-nightly:
    <<: *L0_TEST
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--P40_R384_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--P40_R384_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--P40_R384_2GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--P40_R384_2GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### M40 runs ####
tests_L0--M40_R384_2GPU--torch-nightly:
    <<: *L0_TEST
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L0_test_variables

tests_L1_cross_product--M40_R384_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--M40_R384_2GPU--torch-nightly:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--M40_R384_2GPU--torch-nightly:
    <<: *DISTRIBUTED_DDP
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--M40_R384_2GPU--torch-nightly:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-nightly
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

###########################
# Test runs for PyTorch 1.0
###########################
tests_L0--TU102_R410_2GPU--torch-1-0:
    <<: *L0_TEST
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--TU102_R410_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--TU102_R410_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--TU102_R410_2GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--TU102_R410_2GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *TU102_R410_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### Turing (TU104) runs ####
tests_L0--TU104_R418_2GPU--torch-1-0:
    <<: *L0_TEST
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--TU104_R418_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--TU104_R418_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--TU104_R418_2GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--TU104_R418_2GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *TU104_R418_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### Volta runs ####
tests_L0--V100_R410_4GPU--torch-1-0:
    <<: *L0_TEST
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--V100_R410_4GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--V100_R410_4GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--V100_R410_4GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--V100_R410_4GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *V100_R410_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables

#### P100 runs ####
tests_L0--P100_R384_4GPU--torch-1-0:
    <<: *L0_TEST
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--P100_R384_4GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--P100_R384_4GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--P100_R384_4GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--P100_R384_4GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *P100_R384_4GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables

#### P40 runs ####
tests_L0--P40_R384_2GPU--torch-1-0:
    <<: *L0_TEST
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--P40_R384_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--P40_R384_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--P40_R384_2GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--P40_R384_2GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *P40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64

#### M40 runs ####
tests_L0--M40_R384_2GPU--torch-1-0:
    <<: *L0_TEST
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L0_test_variables

tests_L1_cross_product--M40_R384_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_test_variables

tests_L1_cross_product_distributed--M40_R384_2GPU--torch-1-0:
    <<: *L1_CROSS_PRODUCT_DISTRIBUTED
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *L1_cross_product_distributed_test_variables

tests_distributed_ddp--M40_R384_2GPU--torch-1-0:
    <<: *DISTRIBUTED_DDP
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_ddp_test_variables

tests_distributed_synced_batchnorm--M40_R384_2GPU--torch-1-0:
    <<: *DISTRIBUTED_SYNCED_BATCHNORM
    <<: *M40_R384_2GPU
    variables:
      APEX_CONTAINER_TAG: torch-1-0
      <<: *distributed_synced_batchnorm_test_variables
      TEST_COMMAND: python single_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py; python -m torch.distributed.launch --nproc_per_node=2 two_gpu_unit_test.py --fp64
